### ISSUE TITLE
SQL database test is failing consistently

### ISSUE THREAD

**Issue by richardszalay** [mspnp/semantic-logging#29]
The error I'm seeing is:

```
TestCleanup method Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Tests.EventListeners.when_receiving_many_events_with_imperative_flush.Cleanup threw exception. System.Data.SqlClient.SqlException: System.Data.SqlClient.SqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---&gt; System.ComponentModel.Win32Exception: The wait operation timed out.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean&amp; dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Tests.TestSupport.LocalDatabaseContext.DetachDatabase() in d:\Dev\OSS\semantic-logging\source\Tests\SemanticLogging.Tests\TestSupport\LocalDatabaseContext.cs:line 76
   at Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Tests.TestSupport.LocalDatabaseContext.OnCleanup() in d:\Dev\OSS\semantic-logging\source\Tests\SemanticLogging.Tests\TestSupport\LocalDatabaseContext.cs:line 58
   at Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Tests.EventListeners.when_receiving_many_events_with_imperative_flush.OnCleanup() in d:\Dev\OSS\semantic-logging\source\Tests\SemanticLogging.Tests\UsingEventListener\SqlDatabaseEventListenerTests.cs:line 46
   at Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Tests.TestSupport.ContextBase.Cleanup() in d:\Dev\OSS\semantic-logging\source\Tests\SemanticLogging.Tests\TestSupport\ContextBase.cs:line 20
```

Note that it is only failing in `DetachDatabase`, which is after the `SET SINGLE_USER` command and the first command to be executed on the `master` database.

**Comment by bennage** [comment]
Please see the note on #91. We are no longer working on Semantic Logging.
