### ISSUE TITLE
An unhandled fault was detected in the processing task for the trace session 'Microsoft-SemanticLogging-Etw-svcRuntime'. Message: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by gamepop** [mspnp/semantic-logging#90]
Semantic Logging out of process service is stopping to process any events after we see this error in the Event log , What can be apparent cause for this.  

ProviderId : d1ed7ec7-5701-5554-2c5e-796dc42511c5
EventId : 801
Keywords : 4
Level : Critical
Message : An unhandled fault was detected in the processing task for the trace session 'Microsoft-SemanticLogging-Etw-svcRuntime'. Message: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Schema.EventSourceSchemaReader.GetSchema(String manifest)
   at Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Etw.TraceEventServiceWorker.OnManifestReceived(ProviderManifest providerManifest)
   at Microsoft.Diagnostics.Tracing.Parsers.DynamicTraceEventParser.AddDynamicProvider(ProviderManifest providerManifest, Boolean noThrowOnError)
   at Microsoft.Diagnostics.Tracing.Parsers.DynamicTraceEventParser.CheckForDynamicManifest(TraceEvent data)
   at System.Action`1.Invoke(T obj)
   at Microsoft.Diagnostics.Tracing.Parsers.DynamicTraceEventData.Dispatch()
   at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.Dispatch(TraceEvent anEvent)
   at Microsoft.Diagnostics.Tracing.TraceEventNativeMethods.ProcessTrace(UInt64[] handleArray, UInt32 handleCount, IntPtr StartTime, IntPtr EndTime)
   at Microsoft.Diagnostics.Tracing.ETWTraceEventSource.ProcessOneFile()
   at Microsoft.Diagnostics.Tracing.ETWTraceEventSource.Process()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Schema.EventSourceSchemaReader.GetSchema(String manifest)
   at Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Etw.TraceEventServiceWorker.OnManifestReceived(ProviderManifest providerManifest)
   at Microsoft.Diagnostics.Tracing.Parsers.DynamicTraceEventParser.AddDynamicProvider(ProviderManifest providerManifest, Boolean noThrowOnError)
   at Microsoft.Diagnostics.Tracing.Parsers.DynamicTraceEventParser.CheckForDynamicManifest(TraceEvent data)
   at System.Action`1.Invoke(T obj)
   at Microsoft.Diagnostics.Tracing.Parsers.DynamicTraceEventData.Dispatch()
   at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.Dispatch(TraceEvent anEvent)
   at Microsoft.Diagnostics.Tracing.TraceEventNativeMethods.ProcessTrace(UInt64[] handleArray, UInt32 handleCount, IntPtr StartTime, IntPtr EndTime)
   at Microsoft.Diagnostics.Tracing.ETWTraceEventSource.ProcessOneFile()
   at Microsoft.Diagnostics.Tracing.ETWTraceEventSource.Process()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Opcode : Info
Task : 64733
Version : 0
Payload : [sessionName : Microsoft-SemanticLogging-Etw-svcRuntime] [message : System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Schema.EventSourceSchemaReader.GetSchema(String manifest)
   at Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Etw.TraceEventServiceWorker.OnManifestReceived(ProviderManifest providerManifest)
   at Microsoft.Diagnostics.Tracing.Parsers.DynamicTraceEventParser.AddDynamicProvider(ProviderManifest providerManifest, Boolean noThrowOnError)
   at Microsoft.Diagnostics.Tracing.Parsers.DynamicTraceEventParser.CheckForDynamicManifest(TraceEvent data)
   at System.Action`1.Invoke(T obj)
   at Microsoft.Diagnostics.Tracing.Parsers.DynamicTraceEventData.Dispatch()
   at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.Dispatch(TraceEvent anEvent)
   at Microsoft.Diagnostics.Tracing.TraceEventNativeMethods.ProcessTrace(UInt64[] handleArray, UInt32 handleCount, IntPtr StartTime, IntPtr EndTime)
   at Microsoft.Diagnostics.Tracing.ETWTraceEventSource.ProcessOneFile()
   at Microsoft.Diagnostics.Tracing.ETWTraceEventSource.Process()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Schema.EventSourceSchemaReader.GetSchema(String manifest)
   at Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Etw.TraceEventServiceWorker.OnManifestReceived(ProviderManifest providerManifest)
   at Microsoft.Diagnostics.Tracing.Parsers.DynamicTraceEventParser.AddDynamicProvider(ProviderManifest providerManifest, Boolean noThrowOnError)
   at Microsoft.Diagnostics.Tracing.Parsers.DynamicTraceEventParser.CheckForDynamicManifest(TraceEvent data)
   at System.Action`1.Invoke(T obj)
   at Microsoft.Diagnostics.Tracing.Parsers.DynamicTraceEventData.Dispatch()
   at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.Dispatch(TraceEvent anEvent)
   at Microsoft.Diagnostics.Tracing.TraceEventNativeMethods.ProcessTrace(UInt64[] handleArray, UInt32 handleCount, IntPtr StartTime, IntPtr EndTime)
   at Microsoft.Diagnostics.Tracing.ETWTraceEventSource.ProcessOneFile()
   at Microsoft.Diagnostics.Tracing.ETWTraceEventSource.Process()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
] 
EventName : TraceEventServiceProcessTaskFaultInfo
Timestamp : 2016-07-22T20:07:13.7556543Z
ProcessId : 6104
ThreadId : 1492

**Comment by SayahImadWolf** [comment]
Hi , 
I have the same problem  .

**Comment by bennage** [comment]
Please see the note on #91. We are no longer working on Semantic Logging.
